import esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

const Obsidian = require('obsidian');
`;

const prod = (process.argv[2] === 'production');

if (process.argv[2] === 'watch') {
	esbuild.context({
		banner: {
			js: banner,
		},
		entryPoints: ['main.ts'],
		bundle: true,
		external: ['obsidian'],
		format: 'cjs',
		target: 'es2020',
		logLevel: "info",
		sourcemap: 'inline',
		treeShaking: true,
		outfile: 'main.js',
	}).then(ctx => ctx.watch()).catch(() => process.exit(1));
} else {
	esbuild.build({
		banner: {
			js: banner,
		},
		entryPoints: ['main.ts'],
		bundle: true,
		external: ['obsidian'],
		format: 'cjs',
		target: 'es2020',
		logLevel: "info",
		sourcemap: prod ? false : 'inline',
		treeShaking: true,
		outfile: 'main.js',
	}).catch(() => process.exit(1));
}
